# Generated by Django 5.2.2 on 2025-06-10 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, help_text='Requerido. 30 caracteres o menos. Letras, números y @/./+/-/_ solamente.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario solo puede contener letras, números y los caracteres @/./+/-/_.', regex='^[\\w.@+-]+$')], verbose_name='username'),
        ),
    ]
