# Generated by Django 5.2.2 on 2025-06-13 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_user_options_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['nombre'], 'verbose_name': 'tienda', 'verbose_name_plural': 'tiendas'},
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.AddField(
            model_name='store',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='propietario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='telefono',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
